<?php
/**
 * 
 */


// For testing - Uncomment if you get a blank page. This code will often show errors.
error_reporting(E_ALL ^ E_NOTICE  ^ E_WARNING);
ini_set('display_errors', 1);



/**
 * theme customization
 */
include __DIR__ . '/lib/theme-support.php';
include __DIR__ . '/lib/remove-actions-and-filters.php';
include __DIR__ . '/lib/js-and-css-scripts.php';
include __DIR__ . '/lib/menus-and-sidebars.php';
include __DIR__ . '/lib/post-types.php';



/**
 * settings for plugins
 */
include __DIR__ . '/lib/plugin-acf-settings.php';



/**
 * functions to clean up wp-admin, and html generated by wordpress
 */
include __DIR__ . '/lib/admin-cleanup.php';
include __DIR__ . '/lib/html-cleanup.php';



/**
 * helder classes
 */
include __DIR__ . '/lib/walker-nav-menu-bootstrap.php';




